### ISSUE TITLE
Filtre sur les opérateurs

### ISSUE THREAD

**Issue by fr33mobile** [fraetech/maj-hebdo#1]
Super intéressant. Il serait possible de rajouter un filtre pour ne visualiser que les informations d'un opérateur ?

**Comment by fraetech** [comment]
Bien pris en compte, je fais ça asap.

**Comment by fraetech** [comment]
J'ai creusé tout ça en ce début de semaine. J'ai trouvé quelques pistes en attendant mieux : 
- Remplacer le filtre par action en filtre par opérateur (et donc mettre plusieurs actions dans un même point).
- Effectuer un filtre différent par combinaison opérateur-action (ce qui peut rendre la liste assez longue).
- Créer soit : une carte par opérateur en gardant à l'intérieur de chaque carte les filtres par action **OU** une carte par action en mettant à l'intérieur de chaque carte un filtre par opérateur, multiplication des cartes, pas terrible non plus.

En effet, pour l'instant je ne peux pas de manière simple combiner les deux filtres (actions & opés) sur la même carte. Encore faut-il que je trouve le moyen de contourner ce point de blocage.
Très précisément je ne peux pas ajouter un marqueur Leaflet à deux FeatureGroup en même temps, pour ceux qui connaissent.

Donc en attendant je ne sais pas si tu as une solution que tu préfères parmi celles listées ci-dessus, la "moins pire" de toutes, selon toi. Je pense plutôt à la première ou la troisième, mais je suis indécis.

**Comment by fraetech** [comment]
Option retenue : la 3e !
Cela permettra d'implémenter une carte par opérateur (une par opérateur de France métropolitaine, dans un premier temps et éventuellement une supplémentaire pour les opérateurs d'outre-mer).
Je pense garder au sein de chaque carte le même filtre par action qu'actuellement. A voir. Le seul bémol c'est qu'au lieu de générer une carte le programme devra en générer au moins cinq, ce qui le rendra nécessairement plus lent.
En attendant c'est sous cette forme-là que ça devrait se présenter (un lien par carte supplémentaire, voir les liens barrés) : 
![image](https://github.com/user-attachments/assets/a87d9f0a-402f-4059-b368-f471f4531ed5)

**Comment by fr33mobile** [comment]
Nickel.
Merci.

**Comment by fraetech** [comment]
Hello,
Option 3 implémentée. On dispose à présent d'une carte "principale" accessible via https://fraetech.github.io/maj-hebdo/
En plus de cette carte il y a désormais une carte par opérateur de France métropolitaine (Bouygues, Free, Orange et SFR).
Les cartes sont accessibles via https://fraetech.github.io/maj-hebdo/[opérateur].html, en plus de l'être via les liens présents dans le petit pop-up sur chaque carte.
A noter :
- L'opérateur Telco OI a été intégré à la carte Free.
- L'opérateur SRR a été intégré à la carte SFR.
C'est en prod ! Preneur de tout retour.
![image](https://github.com/user-attachments/assets/26f7c527-3a0a-42a8-8a46-9ca58b06f7e9)
